FEATURE_REGISTRY = {
    "Dashboard": {
        "icon": "🏠",
        "features": [
            "Executive Summary",
            "Revenue Overview",
            "Signup Overview",
            "Upload Overview",
            "Paid Customer Overview",
            "Platform Health",
            "Latest Data Month",
            "System Status",
        ],
    },
    "KPI": {
        "icon": "📊",
        "features": [
            "Dashboard",
            "Browse Data",
            "EDA Lab",
            "Manual Override",
            "Alerts",
            "Pattern Analysis UI",
            "Trend Analysis",
            "Predictions",
            "Data Quality",
            "Lead Sources",
            "Traffic Attribution",
            "Daily Counts",
            "Monthly Counts",
            "Full Reports UI",
            "CSV Export",
            "Override Audit Log",
            "Duplicate Detection",
            "Spam Rate Analysis",
            "Internal Email Exclusion",
        ],
    },
    "Google Analytics": {
        "icon": "📈",
        "features": [
            "Overview",
            "Traffic Source Tables",
            "Pages Table",
            "Events Table",
            "Geo Charts",
            "Device Charts",
            "Channel Charts",
            "Countries",
            "Devices",
            "Channels",
            "Smart QA UI",
            "Strategic QA",
            "Source Intelligence",
            "Pattern Analysis",
            "Top Landing Pages",
            "UTM Campaigns",
            "Conversion Attribution",
        ],
    },
    "YouTube": {
        "icon": "📺",
        "features": [
            "Channel Overview",
            "Full Videos Table",
            "Analytics Tab",
            "Audience Tab",
            "Revenue Tab",
            "Traffic Tab",
            "Playlists Tab",
            "AI Video Analysis",
            "Best/Worst Videos",
            "OAuth Status",
            "Engagement Ranking",
            "Views Trend",
            "Comments/Likes Analysis",
            "Video Search",
            "Video Export",
        ],
    },
    "LinkedIn": {
        "icon": "💼",
        "features": [
            "Full Command Center",
            "Posts Table",
            "Followers History",
            "Visitors",
            "Competitors",
            "Search Appearances",
            "Export Analytics",
            "Daily Pipeline",
            "Growth History",
            "Engagement Ranking",
            "Top Posts",
            "Follower Delta",
            "Post Search",
        ],
    },
    "Customer Success": {
        "icon": "🎯",
        "features": [
            "Full Customer Browser",
            "Master Customers",
            "Enriched Customers",
            "Health Score",
            "Retention",
            "Churn",
            "Stripe Status",
            "Upload/Payment Funnel",
            "Customer Timeline",
            "Subscription Status",
            "Revenue Per Customer",
            "At-Risk Customers",
            "CSV Export",
        ],
    },
    "Cross-Platform": {
        "icon": "🔗",
        "features": [
            "Unified Timeline",
            "Correlations",
            "Attribution",
            "Funnel",
            "Growth Analysis",
            "Insights",
            "Platform Health",
            "KPI vs GA4",
            "KPI vs YouTube",
            "KPI vs LinkedIn",
            "Lead Source Attribution",
            "Content Impact Analysis",
        ],
    },
    "AI & Insights": {
        "icon": "🤖",
        "features": [
            "Ask AI",
            "AI KPI",
            "AI YouTube",
            "AI LinkedIn",
            "AI GA4",
            "AI Customer Success",
            "Predictions",
            "Strategic Questions",
            "Smart QA",
            "Anomaly Explanation",
            "Growth Recommendations",
            "Report Summaries",
        ],
    },
    "Custom Modules": {
        "icon": "🧩",
        "features": [
            "Full Create UI",
            "Upload CSV/XLSX",
            "Manage Modules",
            "Auto Insights",
            "Auto Charts",
            "Data Browser",
            "Download CSV",
            "Column Detection",
            "Date Detection",
            "Numeric Detection",
            "Search",
            "Module Deactivation",
        ],
    },
    "Reports": {
        "icon": "📋",
        "features": [
            "KPI Report",
            "Cross-Platform Report",
            "Customer Success Report",
            "YouTube Report",
            "LinkedIn Report",
            "GA4 Report",
            "Export CSV",
            "Export PDF",
            "Scheduled Reports",
            "Email Reports",
            "Report History",
        ],
    },
    "Settings": {
        "icon": "⚙️",
        "features": [
            "User Access",
            "Roles",
            "API Keys",
            "Pipeline Controls",
            "Secrets Status",
            "Cache Clear",
            "Telegram Alerts",
            "System Health",
            "MongoDB Health",
            "OAuth Status",
            "Audit Logs",
            "Data Freshness",
            "Index Health",
            "Backup Status",
        ],
    },
}


def get_feature_registry():
    return FEATURE_REGISTRY
